### get home page
GET http://localhost:3000

### get signup page

GET http://localhost:3000/auth/signup HTTP/1.1

### get login page

GET http://localhost:3000/auth/login HTTP/1.1

### create blogger

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "firstname":"Saeed",
    "lastname":"Salehi",
    "username":"saeedsalehi",
    "password":"saeedSalehi1234",
    "cellphone":"091222523654",
    "role":"blogger"
}

### login blogger
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username":"saeedsalehi",
    "password":"saeedSalehi1234"
}

###get profile page
GET http://localhost:3000/blogger/profile HTTP/1.1

###delete blogger
DELETE http://localhost:3000/blogger/profile

###get update page
GET http://localhost:3000/blogger/update HTTP/1.1


###update blogger
PUT http://localhost:3000/blogger/update
content-type: application/json

{
    "firstname":"Omid"
}

###logout blogger
GET http://localhost:3000/blogger/logout HTTP/1.1

###########################################################3



###create article
POST http://localhost:3000/article HTTP/1.1
content-type: application/json


{
    "title":"On 31 December 2019,",
    "text":"On 31 December 2019, WHO was informed of cases of pneumonia of coronavirus in Wuhan City, China. The World Health Organization declared the outbreak a Public Health Emergency of International Concern on 30 January 2020, and a pandemic on 11 March 2020. On 19 February 2020, Iran reported its first confirmed cases of infections in Qom and was written in newspapers that COVID-19 outbreak hits Iran."
}

###update article
PUT http://localhost:3000/article/621dc42b4661cf14b08160fe HTTP/1.1
content-type: application/json

{
    "title":"On 31 December 2019,",
    "text":"On 31 December 2019, WHO was informed of cases of pneumonia of coronavirus in Wuhan City, China. The World Health Organization declared the outbreak a Public Health Emergency of International Concern on 30 January 2020, and a pandemic on 11 March 2020. On 19 February 2020, Iran reported its first confirmed cases of infections in Qom and was written in newspapers that COVID-19 outbreak hits Iran."
}

###delete article
DELETE http://localhost:3000/article/621ddd65523bc00d896eaf71 HTTP/1.1


##################################################

###login as an admin
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username":"administrator",
    "password":"admiN1234"
}


### get admin profile page
GET http://localhost:3000/admin/profile HTTP/1.1

###reset blogger password
PUT http://localhost:3000/admin/profile/621dd4b62b37d9d729f5851c HTTP/1.1
content-type: application/json

{
    "password":"saeedSalehi5678"
}

###delete a blogger
DELETE http://localhost:3000/admin/profile/621b572e2b099885f12e1522 HTTP/1.1

###logout
GET http://localhost:3000/admin/logout HTTP/1.1